Fix #5793: Update workflows to Ubuntu 24.04 (#5795)
Fixes #5793 

<!-- READ ME FIRST: Please fill in the explanation section below and
check off every point from the Essential Checklist! -->
## Explanation
<!--
- Explain what your PR does. If this PR fixes an existing bug, please
include
- "Fixes #bugnum:" in the explanation so that GitHub can auto-close the
issue
  - when this PR is merged.
  -->

Updates workflows to use `ubuntu-24.04`

Took this to test run and see if it could help unblock other PRs. 

- ~~Updated the workflows to use the `ubuntu-latest` version rather
setting a hard-coded version to stay updated with current versions and
to minimize manual updates over time.~~ Edit: Updated to `ubuntu-24.04`
as just realized that latest version might introduce breaking changes or
future compatibility issues, while hard-coded version being well-tested
would be more stable.
- Noticed that upgrading caused the runner to default to JDK 17,
[ignoring the JDK 11
setup](https://github.com/oppia/oppia-android/actions/runs/14203094048/job/39795027843?pr=5795#step:7:31).
Instead of forcing a fix, removed the JDK setups since Bazel now handles
it remotely.
```
Java home: /usr/lib/jvm/temurin-17-jdk-amd64
openjdk version "17.0.14" 2025-01-21
OpenJDK Runtime Environment Temurin-17.0.14+7 (build 17.0.14+7)
OpenJDK 64-Bit Server VM Temurin-17.0.14+7 (build 17.0.14+7, mixed mode, sharing)
Error: Process completed with exit code 1.
```
- Used the matrix strategy for test builds to simplify the setup and
reduce duplication—it's not directly related to this fix, but I’d been
meaning to try it for a while, and this PR seemed like a good
opportunity to do so.


## Essential Checklist
<!-- Please tick the relevant boxes by putting an "x" in them. -->
- [x] The PR title and explanation each start with "Fix #bugnum: " (If
this PR fixes part of an issue, prefix the title with "Fix part of
#bugnum: ...".)
- [x] Any changes to
[scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets)
files have their rationale included in the PR explanation.
- [x] The PR follows the [style
guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android
Studio
([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and
is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers
([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).